var movieTile = "Amadeus";
movieTile = "Arrival";
movieTile = 1; // You will be able to compile this byt TS will give you an error in the terminal
var numCatLives = 9;
numCatLives += 1;
numCatLives = 'zero'; // You will be able to compile this byt TS will give you an error in the terminal
var gameOver = false;
gameOver = true;
gameOver = 'true'; // You will be able to compile this byt TS will give you an error in the terminal
